<?php
require __DIR__.'/../../includes/app.php';require __DIR__.'/../../includes/maintenance.php';access(false);$error='';$maintenance=($_GET['origen']??'')==='mantenimiento'&&in_array($_SESSION['usuario_rol'],['Administrador','Técnico']);
if($_SERVER['REQUEST_METHOD']==='POST'&&!($error=validate_form($pdo,'reportes'))) {
    try{$id=create_report($pdo,(int)$_POST['equipo_id'],(int)$_SESSION['usuario_id'],trim($_POST['descripcion']));redirect_to($maintenance?'../mantenimiento/assign.php?reporte_id='.$id:'view.php?id='.$id,'Reporte registrado.');}
    catch(DomainException $e){$error=$e->getMessage();}catch(Throwable $e){$error='No se pudo guardar el reporte.';}
}
$equipment=rows("SELECT e.id,CONCAT(e.codigo,' · ',COALESCE(NULLIF(e.nombre,''),CONCAT(e.marca,' ',e.modelo)),' · ',u.nombre) nombre FROM equipos e JOIN ubicaciones u ON u.id=e.ubicacion_id WHERE e.estado IN ('Activo','En Mantenimiento') AND NOT EXISTS(SELECT 1 FROM prestamos p WHERE p.equipo_id=e.id AND p.devuelto_en IS NULL) AND NOT EXISTS(SELECT 1 FROM reportes r JOIN estados_reporte s ON s.id=r.estado_id WHERE r.equipo_id=e.id AND s.nombre NOT IN ('Reparado','Cerrado')) ORDER BY e.codigo");
page_start($maintenance?'Registrar mantenimiento':'Nuevo reporte de falla','Selecciona el equipo y describe el problema.',button_link('index.php','Volver','arrow-left','btn-light'));if($error)echo '<div class="alert alert-danger">'.h($error).'</div>';
?><form method="POST"><?php echo csrf_field(); ?><section class="form-section"><h2>Información de la falla</h2><?php select_field('equipo_id','Equipo',$equipment,$_POST['equipo_id']??$_GET['equipo_id']??'',true); ?><p class="form-text">Se muestran equipos sin préstamo activo ni otro reporte abierto.</p><label class="form-label mt-4" for="descripcion">Descripción del problema</label><textarea class="form-control" id="descripcion" name="descripcion" rows="6" maxlength="16000" placeholder="Describe la falla y cuándo ocurre…" required><?php echo h($_POST['descripcion']??''); ?></textarea></section><div class="form-footer"><?php echo button_link('index.php','Cancelar','x','btn-light'); ?><button class="btn btn-dark-blue"><i class="bi bi-send"></i> Registrar reporte</button></div></form><?php page_end(); ?>
