<?php
require __DIR__.'/../../includes/app.php';admin_access();$section=$_GET['seccion']??'';$error='';
if($_SERVER['REQUEST_METHOD']==='POST') {
    try {
        if($section==='general'){
            $data=[];foreach(['nombre','institucion','moneda'] as $key){$value=trim($_POST[$key]??'');if($value===''||mb_strlen($value)>100)throw new DomainException('Complete los campos, máximo 100 caracteres.');$data[$key]=$value;}
            $pdo->beginTransaction();foreach($data as $key=>$value)execute_sql('UPDATE configuracion SET valor=? WHERE clave=?',[$value,$key]);$pdo->commit();
        }elseif(in_array($section,['categorias','sedes'],true)) {
            $name=trim($_POST['nombre']??'');if($name===''||mb_strlen($name)>100)throw new DomainException('Ingrese un nombre de hasta 100 caracteres.');$table=$section==='sedes'?'sedes':'tipos_equipo';$id=(int)($_POST['id']??0);
            if(record("SELECT id FROM $table WHERE nombre=? AND id<>?",[$name,$id]))throw new DomainException('El nombre ya existe.');
            if($id)execute_sql("UPDATE $table SET nombre=? WHERE id=?",[$name,$id]);else execute_sql("INSERT INTO $table(nombre) VALUES (?)",[$name]);
        }elseif($section==='notificaciones'){
            execute_sql('UPDATE usuarios SET notificaciones=? WHERE id=?',[(int)(($_POST['notificaciones']??'')==='1'),$_SESSION['usuario_id']]);
        }elseif($section==='apariencia'){
            $v=$_POST['apariencia']??'claro';if(!in_array($v,['claro','compacto'],true))throw new DomainException('Preferencia inválida.');execute_sql('UPDATE usuarios SET apariencia=? WHERE id=?',[$v,$_SESSION['usuario_id']]);
        }elseif($section==='base-datos'){
            require __DIR__.'/../../includes/schema.php';header('Content-Type: application/sql');header('Content-Disposition: attachment; filename="InventIC-respaldo-'.date('Ymd-His').'.sql"');echo backup_database($pdo);exit;
        }else{throw new DomainException('Acción no disponible.');}
        redirect_to('?seccion='.urlencode($section),'Configuración guardada.');
    }catch(DomainException $e){$error=$e->getMessage();}catch(PDOException $e){if($pdo->inTransaction())$pdo->rollBack();$error='No se pudo guardar la configuración.';}
}
page_start('Configuración','Administra los aspectos generales del sistema.',$section?button_link('index.php','Configuración','arrow-left','btn-light'):'');if($error)echo '<div class="alert alert-danger">'.h($error).'</div>';
if(!$section){$tiles=[['general','General','Nombre e información','chat-left-text'],['usuarios','Usuarios','Administrar usuarios','people-fill'],['roles','Roles y permisos','Consultar reglas del sistema','lock-fill'],['categorias','Categorías','Gestionar categorías','boxes'],['sedes','Sedes','Administrar sedes','buildings-fill'],['notificaciones','Notificaciones','Configurar alertas del panel','bell'],['base-datos','Base de datos','Copias de seguridad','database-fill'],['apariencia','Apariencia','Personalizar el sistema','brush-fill']];echo '<div class="settings-grid">';foreach($tiles as [$key,$label,$text,$icon])echo '<a class="settings-tile" href="'.($key==='usuarios'?'../usuarios/index.php':'?seccion='.$key).'"><i class="bi bi-'.$icon.'"></i><strong>'.$label.'</strong><span>'.$text.'</span></a>';echo '</div>';page_end();exit;}
?>
<section class="surface">
<?php if($section==='general'): $config=$pdo->query('SELECT clave,valor FROM configuracion')->fetchAll(PDO::FETCH_KEY_PAIR); ?><h2>Información general</h2><form method="POST"><?php echo csrf_field(); ?><div class="field-grid"><?php field('nombre','Nombre del sistema',$config['nombre'],'text',true);field('institucion','Institución',$config['institucion'],'text',true);field('moneda','Moneda',$config['moneda'],'text',true); ?></div><div class="form-footer"><button class="btn btn-dark-blue">Guardar cambios</button></div></form>
<?php elseif(in_array($section,['categorias','sedes'])): $table=$section==='sedes'?'sedes':'tipos_equipo';$editing=record("SELECT id,nombre FROM $table WHERE id=?",[(int)($_GET['editar']??0)]); ?><h2><?php echo $section==='sedes'?'Sedes':'Categorías de equipos'; ?></h2><form method="POST" class="search-form mb-4"><?php echo csrf_field(); ?><input type="hidden" name="id" value="<?php echo $editing['id']??0; ?>"><input class="form-control w-auto" name="nombre" aria-label="Nombre" placeholder="Nombre" value="<?php echo h($editing['nombre']??''); ?>" maxlength="100" required><button class="btn btn-dark-blue"><?php echo $editing?'Guardar':'Agregar'; ?></button></form><div class="table-responsive"><table class="table-custom"><thead><tr><th>Nombre</th><th>Acciones</th></tr></thead><tbody><?php foreach(rows("SELECT id,nombre FROM $table ORDER BY nombre") as $r)echo '<tr><td>'.h($r['nombre']).'</td><td><a class="btn btn-light btn-sm" href="?seccion='.$section.'&editar='.$r['id'].'">Editar</a></td></tr>'; ?></tbody></table></div>
<?php elseif($section==='roles'): ?><h2>Roles y permisos</h2><div class="table-responsive"><table class="table-custom"><thead><tr><th>Rol</th><th>Permisos</th></tr></thead><tbody><tr><td>Administrador</td><td>Inventario, préstamos, mantenimiento, sedes, reportes, usuarios, configuración y eliminaciones protegidas.</td></tr><tr><td>Técnico</td><td>Inventario, préstamos, ubicaciones, reportes y mantenimiento. Sin gestión de usuarios ni eliminaciones.</td></tr><tr><td>Docente</td><td>Reportar fallas, consultar sus propios reportes y editar su perfil.</td></tr></tbody></table></div><p class="text-muted">Estas reglas se aplican en el servidor. Asigna el rol de cada persona en Usuarios.</p>
<?php elseif($section==='notificaciones'): $u=record('SELECT notificaciones FROM usuarios WHERE id=?',[$_SESSION['usuario_id']]); ?><h2>Alertas del panel</h2><form method="POST"><?php echo csrf_field(); ?><label><input type="checkbox" name="notificaciones" value="1" <?php echo $u['notificaciones']?'checked':''; ?>> Mostrar aviso de préstamos atrasados al iniciar sesión</label><div class="form-footer"><button class="btn btn-dark-blue">Guardar preferencia</button></div></form>
<?php elseif($section==='apariencia'): $u=record('SELECT apariencia FROM usuarios WHERE id=?',[$_SESSION['usuario_id']]); ?><h2>Apariencia</h2><form method="POST"><?php echo csrf_field();select_field('apariencia','Densidad de la interfaz',[['id'=>'claro','nombre'=>'Estándar'],['id'=>'compacto','nombre'=>'Compacta']],$u['apariencia'],true); ?><div class="form-footer"><button class="btn btn-dark-blue">Aplicar</button></div></form>
<?php elseif($section==='base-datos'): ?><h2>Copia de seguridad</h2><p class="text-muted">Descarga el esquema y los datos actuales. Conserva este archivo en un lugar privado: contiene información de usuarios.</p><form method="POST"><?php echo csrf_field(); ?><button class="btn btn-dark-blue"><i class="bi bi-download"></i> Descargar respaldo SQL</button></form>
<?php else: ?><p>Sección no encontrada.</p><?php endif; ?></section><?php page_end(); ?>
