<?php
require __DIR__.'/../../includes/app.php';access();
$state=$_GET['estado']??'Todos';$search=trim($_GET['q']??'');$category=(int)($_GET['tipo']??0);$site=(int)($_GET['sede']??0);$location=(int)($_GET['ubicacion']??0);
$c=inventory_counts();$sites=record('SELECT COUNT(*) total FROM sedes')['total'];
page_start('Inventario de equipos',$c['total'].' equipos registrados en '.$sites.' sedes',button_link('create.php','Registrar equipo'));inventory_cards($c);
?>
<form class="search-form" method="GET"><input type="hidden" name="estado" value="<?php echo h($state); ?>"><div class="search-box"><i class="bi bi-search"></i><input name="q" aria-label="Buscar equipos" placeholder="Buscar por código, modelo o aula…" value="<?php echo h($search); ?>"></div><select class="form-select" name="tipo" aria-label="Categoría"><option value="0">Categoría</option><?php foreach(rows('SELECT id,nombre FROM tipos_equipo ORDER BY nombre') as $v)echo '<option value="'.$v['id'].'" '.($category==$v['id']?'selected':'').'>'.h($v['nombre']).'</option>'; ?></select><select class="form-select" name="sede" aria-label="Sede"><option value="0">Sede</option><?php foreach(rows('SELECT id,nombre FROM sedes ORDER BY nombre') as $v)echo '<option value="'.$v['id'].'" '.($site==$v['id']?'selected':'').'>'.h($v['nombre']).'</option>'; ?></select><button class="btn btn-light">Buscar</button><a class="btn btn-light" href="index.php">Limpiar</a></form>
<?php filter_tabs(['Todos','Disponibles','Prestados','Mantenimiento','Inactivos'],$state);
$where=[];$params=[];$states=['Disponibles'=>"e.estado='Activo' AND p.id IS NULL",'Prestados'=>'p.id IS NOT NULL','Mantenimiento'=>"e.estado='En Mantenimiento'",'Inactivos'=>"e.estado='Inactivo'"];
if(isset($states[$state]))$where[]=$states[$state];
if($search!==''){$where[]='(e.codigo LIKE ? OR e.nombre LIKE ? OR e.modelo LIKE ? OR e.marca LIKE ? OR u.nombre LIKE ?)';$params=array_fill(0,5,'%'.$search.'%');}
foreach(['e.tipo_id'=>$category,'u.sede_id'=>$site,'e.ubicacion_id'=>$location] as $column=>$id)if($id){$where[]=$column.'=?';$params[]=$id;}
$from=equipment_from().($where?' WHERE '.implode(' AND ',$where):'');$total=(int)record('SELECT COUNT(*) total'.$from,$params)['total'];$page=min(max(1,(int)($_GET['page']??1)),max(1,(int)ceil($total/20)));
$list=rows('SELECT e.*,t.nombre categoria,u.nombre ubicacion,COALESCE(b.nombre,r.nombre,\'Sin asignar\') responsable,'.equipment_status_sql().' estado_visual'.$from.' ORDER BY e.codigo LIMIT 20 OFFSET '.(($page-1)*20),$params);
?><div class="table-responsive"><table class="table-custom"><thead><tr><th>Código</th><th>Equipo</th><th>Ubicación</th><th>Asignado a</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
<?php foreach($list as $e): ?><tr><td><a href="view.php?id=<?php echo $e['id']; ?>"><?php echo h($e['codigo']); ?></a></td><td><div class="inventory-device"><span class="inventory-device-media"><?php if($e['fotografia']): ?><img src="photo.php?id=<?php echo $e['id']; ?>" alt="<?php echo h($e['nombre']?:$e['categoria']); ?>" width="56" height="56" loading="lazy" decoding="async"><?php else: ?><span class="inventory-device-icon"><i class="bi bi-<?php echo $e['categoria']==='Impresora'?'printer':'display'; ?>"></i></span><?php endif; ?></span><span><strong><?php echo h($e['nombre']?:trim($e['marca'].' '.$e['modelo'])?:$e['categoria']); ?></strong><small><?php echo h($e['categoria']); ?></small></span></div></td><td><?php echo h($e['ubicacion']); ?></td><td><?php echo h($e['responsable']); ?></td><td><?php echo badge($e['estado_visual']); ?></td><td><div class="table-action"><a title="Detalle de equipo" href="view.php?id=<?php echo $e['id']; ?>"><i class="bi bi-three-dots"></i></a><a aria-label="Editar equipo <?php echo h($e['codigo']); ?>" href="edit.php?id=<?php echo $e['id']; ?>"><i class="bi bi-pencil"></i></a></div></td></tr><?php endforeach;if(!$list)empty_row(6,'No hay equipos encontrados.'); ?></tbody></table></div><?php pagination($total,$page);page_end(); ?>
