<?php
require __DIR__.'/../../includes/app.php';access();$id=(int)($_GET['id']??0);
$e=record('SELECT e.*,t.nombre categoria,u.nombre ubicacion,s.nombre sede,COALESCE(b.nombre,r.nombre,\'Sin asignar\') responsable,'.equipment_status_sql().' estado_visual'.equipment_from().' WHERE e.id=?',[$id]);
if(!$e){http_response_code(404);page_start('Equipo no encontrado');page_end();exit;}
$tab=$_GET['tab']??'Información';$name=$e['nombre']?:trim($e['marca'].' '.$e['modelo'])?:$e['categoria'];
page_start('Detalle de equipo','',button_link('index.php','Inventario','arrow-left','btn-light').button_link('edit.php?id='.$id,'Editar','pencil','btn-light'));
?><div class="equipment-hero"><div><?php if($e['fotografia']): ?><img class="equipment-photo" src="photo.php?id=<?php echo $id; ?>" alt="<?php echo h($name); ?>"><?php else: ?><div class="device-placeholder"><i class="bi bi-laptop"></i></div><?php endif; ?></div><div><h2 class="h5 fw-bold"><?php echo h($name); ?></h2><p><span class="badge text-bg-light"><?php echo h($e['codigo']); ?></span> <?php echo badge($e['estado_visual']); ?></p><dl class="detail-grid"><?php foreach(['Marca'=>$e['marca'],'Categoría'=>$e['categoria'],'Modelo'=>$e['modelo'],'Ubicación'=>$e['ubicacion'],'Serie'=>$e['numero_serie'],'Responsable'=>$e['responsable']] as $k=>$v)echo '<div><dt>'.h($k).'</dt><dd>'.h($v?:'—').'</dd></div>'; ?></dl></div></div>
<nav class="tabs"><?php foreach(['Información','Préstamos','Mantenimientos','Historial'] as $label)echo '<a class="'.($tab===$label?'active':'').'" href="?'.h(http_build_query(['id'=>$id,'tab'=>$label])).'">'.$label.'</a>'; ?></nav>
<?php if($tab==='Información'): ?><section class="surface"><dl class="detail-grid"><?php foreach(['Fecha de adquisición'=>$e['fecha_adquisicion']?:'No registrada','Precio'=>$e['precio']!==null?number_format((float)$e['precio'],2):'No registrado','Proveedor'=>$e['proveedor']?:'No registrado','Sede'=>$e['sede'],'Observaciones'=>$e['observaciones']?:'Sin observaciones'] as $k=>$v)echo '<div><dt>'.h($k).'</dt><dd>'.nl2br(h($v)).'</dd></div>'; ?></dl></section>
<?php elseif($tab==='Préstamos'): $list=rows('SELECT p.*,u.nombre FROM prestamos p JOIN usuarios u ON u.id=p.usuario_id WHERE p.equipo_id=? ORDER BY p.id DESC',[$id]); ?><div class="table-responsive"><table class="table-custom"><thead><tr><th>Prestado a</th><th>Préstamo</th><th>Devolución prevista</th><th>Estado</th></tr></thead><tbody><?php foreach($list as $p)echo '<tr><td>'.h($p['nombre']).'</td><td>'.h($p['fecha_prestamo']).'</td><td>'.h($p['fecha_devolucion']).'</td><td>'.badge($p['devuelto_en']?'Devuelto':'Prestado').'</td></tr>';if(!$list)empty_row(4,'Sin préstamos registrados.'); ?></tbody></table></div>
<?php elseif($tab==='Mantenimientos'): $list=rows('SELECT r.id,r.descripcion,s.nombre estado,r.fecha_reporte FROM reportes r JOIN estados_reporte s ON s.id=r.estado_id WHERE r.equipo_id=? ORDER BY r.id DESC',[$id]); ?><div class="table-responsive"><table class="table-custom"><thead><tr><th>Reporte</th><th>Problema</th><th>Fecha</th><th>Estado</th></tr></thead><tbody><?php foreach($list as $r)echo '<tr><td><a href="../reportes/view.php?id='.$r['id'].'">#'.$r['id'].'</a></td><td>'.h($r['descripcion']).'</td><td>'.h($r['fecha_reporte']).'</td><td>'.badge($r['estado']).'</td></tr>';if(!$list)empty_row(4,'Sin mantenimientos registrados.'); ?></tbody></table></div>
<?php else: ?><section class="surface"><div class="timeline"><?php $list=rows('SELECT * FROM actividad WHERE equipo_id=? ORDER BY fecha DESC LIMIT 100',[$id]);foreach($list as $a)echo '<div class="timeline-item"><i class="bi bi-clock-history"></i><span>'.h($a['descripcion']).'</span><small>'.h($a['fecha']).'</small></div>';if(!$list)echo '<p class="text-muted">Sin movimientos registrados.</p>'; ?></div></section><?php endif; ?>
<div class="form-footer"><?php if($e['estado_visual']==='Activo')echo button_link('../prestamos/create.php?equipo_id='.$id,'Prestar equipo','box-arrow-up-right');echo button_link('../reportes/create.php?equipo_id='.$id,'Reportar falla','exclamation-circle','btn-light');if($_SESSION['usuario_rol']==='Administrador'): ?><form method="POST" action="delete.php" data-confirm="¿Eliminar el equipo? Se conservará si tiene registros asociados."><?php echo csrf_field(); ?><input type="hidden" name="id" value="<?php echo $id; ?>"><button class="btn btn-danger">Eliminar equipo</button></form><?php endif; ?></div><?php page_end(); ?>
