<?php
require __DIR__.'/../../includes/app.php';require __DIR__.'/../../includes/maintenance.php';access();$id=(int)($_GET['reporte_id']??0);$r=record('SELECT r.*,e.codigo,e.nombre,s.nombre estado FROM reportes r JOIN equipos e ON e.id=r.equipo_id JOIN estados_reporte s ON s.id=r.estado_id WHERE r.id=?',[$id]);if(!$r)redirect_to('index.php');$m=record('SELECT * FROM mantenimientos WHERE reporte_id=?',[$id]);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&!($error=validate_form($pdo,'mantenimiento'))) {
    try{save_maintenance($pdo,$id,(int)$_SESSION['usuario_id'],(int)$_POST['estado_id'],trim($_POST['diagnostico']),trim($_POST['solucion']));redirect_to('../reportes/view.php?id='.$id,'Mantenimiento actualizado.');}
    catch(DomainException $e){$error=$e->getMessage();}catch(Throwable $e){$error='No se pudo actualizar el mantenimiento.';}
}
page_start('Actualizar mantenimiento',$r['codigo'].' · Reporte #'.$id,button_link('index.php','Mantenimiento','arrow-left','btn-light'));if($error)echo '<div class="alert alert-danger">'.h($error).'</div>';
?><section class="surface mb-3"><h2>Problema reportado</h2><p class="mb-0"><?php echo nl2br(h($r['descripcion'])); ?></p></section>
<?php if($r['estado']==='Cerrado'): ?><div class="alert alert-info">Este reporte está cerrado. Su historial se conserva y no puede modificarse.</div><?php else: ?>
<form method="POST"><?php echo csrf_field(); ?><section class="form-section"><h2>Seguimiento técnico</h2><?php select_field('estado_id','Estado del reporte',rows('SELECT id,nombre FROM estados_reporte ORDER BY id'),$_POST['estado_id']??$r['estado_id'],true); ?><div class="field-grid mt-3"><div><label for="diagnostico" class="form-label">Diagnóstico</label><textarea name="diagnostico" id="diagnostico" class="form-control" rows="5" maxlength="16000"><?php echo h($_POST['diagnostico']??$m['diagnostico']??''); ?></textarea></div><div><label for="solucion" class="form-label">Solución aplicada</label><textarea name="solucion" id="solucion" class="form-control" rows="5" maxlength="16000"><?php echo h($_POST['solucion']??$m['solucion']??''); ?></textarea></div></div><p class="form-text mt-3">Indica la solución antes de marcar como reparado o cerrado. El equipo se libera cuando no quedan fallas abiertas.</p></section><div class="form-footer"><?php echo button_link('../reportes/view.php?id='.$id,'Ver detalle','eye','btn-light'); ?><button class="btn btn-dark-blue">Guardar mantenimiento</button></div></form><?php endif;page_end(); ?>
