<?php
require __DIR__.'/../../includes/app.php';access();$state=$_GET['estado']??'Todos';$search=trim($_GET['q']??'');
$c=record("SELECT COALESCE(SUM(s.nombre NOT IN ('Reparado','Cerrado')),0) active,COALESCE(SUM(s.nombre='Pendiente'),0) pending,COALESCE(SUM(s.nombre IN ('En revisión','En reparación')),0) repairing,COALESCE(SUM(s.nombre IN ('Reparado','Cerrado')),0) completed FROM reportes r JOIN estados_reporte s ON s.id=r.estado_id");
$c['active']=inventory_counts()['maintenance'];
page_start('Mantenimiento','Control y seguimiento de equipos',button_link('create.php','Registrar mantenimiento'));stats_cards([[$c['active'],'En mantenimiento','red','tools'],[$c['pending'],'Pendientes','amber','clipboard'],[$c['repairing'],'En reparación','blue','wrench'],[$c['completed'],'Completados','green','box-seam-fill']]);
?><form class="search-form" method="GET"><input name="estado" type="hidden" value="<?php echo h($state); ?>"><div class="search-box"><i class="bi bi-search"></i><input name="q" aria-label="Buscar mantenimiento" placeholder="Buscar mantenimiento…" value="<?php echo h($search); ?>"></div><button class="btn btn-light">Buscar</button></form><?php
filter_tabs(['Todos','Pendientes','En reparación','Completados'],$state);
$where=['Pendientes'=>"s.nombre='Pendiente'",'En reparación'=>"s.nombre IN ('En revisión','En reparación')",'Completados'=>"s.nombre IN ('Reparado','Cerrado')"][$state]??'1=1';$params=[];
if($search!==''){$where.=' AND (e.codigo LIKE ? OR e.nombre LIKE ? OR r.descripcion LIKE ? OR u.nombre LIKE ?)';$params=array_fill(0,4,'%'.$search.'%');}
$from=' FROM reportes r JOIN equipos e ON e.id=r.equipo_id JOIN estados_reporte s ON s.id=r.estado_id LEFT JOIN mantenimientos m ON m.reporte_id=r.id LEFT JOIN usuarios u ON u.id=m.tecnico_id WHERE '.$where;
$total=(int)record('SELECT COUNT(*) total'.$from,$params)['total'];$page=min(max(1,(int)($_GET['page']??1)),max(1,(int)ceil($total/20)));
$list=rows('SELECT r.*,e.codigo,e.nombre equipo,e.marca,e.modelo,s.nombre estado,u.nombre tecnico'.$from.' ORDER BY r.fecha_reporte DESC,r.id DESC LIMIT 20 OFFSET '.(($page-1)*20),$params);
?><div class="table-responsive"><table class="table-custom"><thead><tr><th>Código</th><th>Equipo</th><th>Problema</th><th>Técnico</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($list as $r): ?><tr><td><?php echo h($r['codigo']); ?></td><td><?php echo h($r['equipo']?:$r['marca'].' '.$r['modelo']); ?></td><td><?php echo h(mb_strimwidth($r['descripcion'],0,65,'…')); ?></td><td><?php echo h($r['tecnico']??'Sin asignar'); ?></td><td><?php echo date('d/m/Y',strtotime($r['fecha_reporte'])); ?></td><td><?php echo badge(in_array($r['estado'],['Reparado','Cerrado'])?'Completado':$r['estado']); ?></td><td><div class="table-action"><a title="Ver mantenimiento" href="../reportes/view.php?id=<?php echo $r['id']; ?>"><i class="bi bi-three-dots"></i></a><?php if($r['estado']!=='Cerrado'): ?><a title="Actualizar mantenimiento" href="assign.php?reporte_id=<?php echo $r['id']; ?>"><i class="bi bi-pencil"></i></a><?php endif; ?></div></td></tr><?php endforeach;if(!$list)empty_row(7,'No hay mantenimientos en esta vista.'); ?></tbody></table></div><?php pagination($total,$page);page_end(); ?>
