<?php
require_once __DIR__.'/app.php';access();$id=$editing?(int)($_GET['id']??0):0;$item=$editing?record('SELECT * FROM ubicaciones WHERE id=?',[$id]):[];if($editing&&!$item)redirect_to('index.php');$error='';
if($_SERVER['REQUEST_METHOD']==='POST') {
    $error=validate_form($pdo,'ubicaciones');
    $site=(int)($_POST['sede_id']??$item['sede_id']??record('SELECT MIN(id) id FROM sedes')['id']);$type=$_POST['tipo']??$item['tipo']??'Aula';
    if(!$error&&(!record('SELECT id FROM sedes WHERE id=?',[$site])||!in_array($type,['Aula','Laboratorio','Sala','Bodega','Oficina','Otro'],true)))$error='Seleccione una sede y un tipo válidos.';
    if(!$error)try{$data=[trim($_POST['nombre']),trim($_POST['descripcion']??''),$site,$type];if($editing)execute_sql('UPDATE ubicaciones SET nombre=?,descripcion=?,sede_id=?,tipo=? WHERE id=?',array_merge($data,[$id]));else execute_sql('INSERT INTO ubicaciones(nombre,descripcion,sede_id,tipo) VALUES (?,?,?,?)',$data);redirect_to('index.php?sede='.$site,'Ubicación guardada.');}catch(PDOException $e){$error='Ya existe una ubicación con ese nombre o los datos no son válidos.';}
}
$v=array_merge($item,$_SERVER['REQUEST_METHOD']==='POST'?$_POST:[]);page_start($editing?'Editar ubicación':'Nueva ubicación','Organiza los espacios de tu institución.',button_link('index.php','Volver','arrow-left','btn-light'));if($error)echo '<div class="alert alert-danger">'.h($error).'</div>';
?><form method="POST"><?php echo csrf_field(); ?><section class="form-section"><h2>Información de ubicación</h2><div class="field-grid"><?php field('nombre','Nombre de la ubicación',$v['nombre']??'','text',true);select_field('sede_id','Sede',rows('SELECT id,nombre FROM sedes ORDER BY nombre'),$v['sede_id']??'',true);select_field('tipo','Tipo',array_map(fn($x)=>['id'=>$x,'nombre'=>$x],['Aula','Laboratorio','Sala','Bodega','Oficina','Otro']),$v['tipo']??'Aula',true); ?></div><label class="form-label mt-3" for="descripcion">Descripción</label><textarea class="form-control" name="descripcion" id="descripcion" rows="4"><?php echo h($v['descripcion']??''); ?></textarea></section><div class="form-footer"><?php echo button_link('index.php','Cancelar','x','btn-light'); ?><button class="btn btn-dark-blue">Guardar ubicación</button></div></form><?php page_end(); ?>
