<?php
require __DIR__.'/../../includes/app.php';access(false);$id=(int)$_SESSION['usuario_id'];$user=record('SELECT u.*,r.nombre rol,s.nombre sede FROM usuarios u JOIN roles r ON r.id=u.rol_id LEFT JOIN sedes s ON s.id=u.sede_id WHERE u.id=?',[$id]);$error='';$mode=$_GET['modo']??'';
if($_SERVER['REQUEST_METHOD']==='POST') {
    try {
        if(($_POST['accion']??'')==='password') {
            if(!password_verify($_POST['actual']??'',$user['password']))throw new DomainException('La contraseña actual es incorrecta.');
            $new=$_POST['nueva']??'';if(strlen($new)<12||strlen($new)>72||$new!==($_POST['confirmar']??''))throw new DomainException('Use entre 12 y 72 bytes y confirme la misma contraseña.');
            $hash=password_hash($new,PASSWORD_DEFAULT);execute_sql('UPDATE usuarios SET password=? WHERE id=?',[$hash,$id]);session_regenerate_id(true);$_SESSION['auth_version']=hash('sha256',$hash);$_SESSION['csrf_token']=bin2hex(random_bytes(32));redirect_to('index.php','Contraseña actualizada. Las otras sesiones deberán iniciar sesión nuevamente.');
        }
        $name=trim($_POST['nombre']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['telefono']??'');$cargo=trim($_POST['cargo']??'');$site=($_POST['sede_id']??'')!==''?(int)$_POST['sede_id']:null;
        if($name===''||mb_strlen($name)>100||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>100||mb_strlen($phone)>30||mb_strlen($cargo)>100)throw new DomainException('Revise nombre, correo, teléfono y cargo.');
        if($site&&!record('SELECT id FROM sedes WHERE id=?',[$site]))throw new DomainException('Sede inválida.');
        execute_sql('UPDATE usuarios SET nombre=?,email=?,telefono=?,cargo=?,sede_id=? WHERE id=?',[$name,$email,$phone,$cargo,$site,$id]);$_SESSION['usuario_nombre']=$name;redirect_to('index.php','Perfil actualizado.');
    }catch(DomainException $e){$error=$e->getMessage();}catch(PDOException $e){$error='El correo ya está registrado o no se pudo guardar el perfil.';}
}
page_start('Mi perfil','Administra tu información personal.');if($error)echo '<div class="alert alert-danger">'.h($error).'</div>';
?><div class="profile-card"><section class="surface"><h2>Información de usuario</h2><div class="profile-heading"><span class="avatar"><?php echo h(mb_strtoupper(mb_substr($user['nombre'],0,1))); ?></span><div><h2><?php echo h($user['nombre']); ?></h2><span class="text-muted"><?php echo h($user['rol']); ?></span></div><?php echo button_link('?modo=editar','Editar perfil','pencil'); ?></div>
<?php if($mode==='editar'): $v=array_merge($user,$_SERVER['REQUEST_METHOD']==='POST'?$_POST:[]); ?><form method="POST"><?php echo csrf_field(); ?><div class="field-grid"><?php field('nombre','Nombre',$v['nombre'],'text',true);field('email','Correo',$v['email'],'email',true);field('telefono','Teléfono',$v['telefono']);field('cargo','Cargo',$v['cargo']);select_field('sede_id','Sede',rows('SELECT id,nombre FROM sedes ORDER BY nombre'),$v['sede_id']); ?></div><div class="form-footer"><?php echo button_link('index.php','Cancelar','x','btn-light'); ?><button class="btn btn-dark-blue">Guardar perfil</button></div></form>
<?php elseif($mode==='password'): ?><form method="POST"><?php echo csrf_field(); ?><input type="hidden" name="accion" value="password"><div class="field-grid"><?php field('actual','Contraseña actual','','password',true);field('nueva','Nueva contraseña','','password',true);field('confirmar','Confirmar contraseña','','password',true); ?></div><div class="form-footer"><button class="btn btn-dark-blue">Cambiar contraseña</button></div></form>
<?php else: ?><dl class="detail-grid"><?php foreach(['Nombre'=>$user['nombre'],'Correo'=>$user['email'],'Teléfono'=>$user['telefono']?:'No registrado','Cargo'=>$user['cargo']?:$user['rol'],'Sede'=>$user['sede']??'Sin asignar','Último acceso'=>$user['ultimo_acceso']??'No registrado'] as $k=>$v)echo '<div><dt>'.h($k).'</dt><dd>'.h($v).'</dd></div>'; ?></dl><?php endif; ?></section><div class="form-footer"><?php echo button_link('?modo=password','Cambiar contraseña','lock','btn-light'); ?><form method="POST" action="<?php echo BASE_URL; ?>/auth/logout.php"><?php echo csrf_field(); ?><button class="btn btn-danger"><i class="bi bi-box-arrow-right"></i> Cerrar sesión</button></form></div></div><?php page_end(); ?>
